--create tablespace coordinadora
CREATE TABLESPACE COORDINADORA DATAFILE 
'coordinadora.dbf' SIZE 3G;

--b. Undo tablespace 

CREATE UNDO TABLESPACE UNDO_TBS datafile
'UNDO_TBS1.dbf' size 100M
AUTOEXTEND OFF;

ALTER SYSTEM SET UNDO_TABLESPACE = UNDO_TBS scope = both;

--c. Bigfile tablespace of 4Gb

CREATE BIGFILE TABLESPACE COORDINADORA2 DATAFILE
'C:\coordinadora2.dbf' SIZE 4G;

-- Usuario amartinezg
CREATE USER amartinezg IDENTIFIED BY amartinezg
DEFAULT TABLESPACE COORDINADORA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON COORDINADORA;

GRANT DBA TO amartinezg;
GRANT CONNECT, RESOURCE TO amartinezg;


---crear 3 perfiles
--a
CREATE PROFILE CLERK LIMIT
SESSIONS_PER_USER 1
CPU_PER_SESSION UNLIMITED
CPU_PER_CALL UNLIMITED
CONNECT_TIME 240
IDLE_TIME 15
PRIVATE_SGA 20 M
FAILED_LOGIN_ATTEMPTS 3
PASSWORD_LIFE_TIME 40
PASSWORD_LOCK_TIME 1
PASSWORD_GRACE_TIME 2;

--b
CREATE PROFILE DEVELOPMENT LIMIT 
SESSIONS_PER_USER 2
CPU_PER_SESSION UNLIMITED
CPU_PER_CALL UNLIMITED
CONNECT_TIME 240
IDLE_TIME 30
PRIVATE_SGA 20 M 
PASSWORD_LIFE_TIME 100
PASSWORD_LOCK_TIME 1
PASSWORD_GRACE_TIME 2;

--c
CREATE PROFILE OPERATIVE LIMIT
SESSIONS_PER_USER 1
CPU_PER_SESSION UNLIMITED
CPU_PER_CALL UNLIMITED
CONNECT_TIME 240
IDLE_TIME 5
PRIVATE_SGA 20 M
FAILED_LOGIN_ATTEMPTS 4
PASSWORD_LIFE_TIME 30
PASSWORD_REUSE_MAX 3
PASSWORD_REUSE_TIME 30
PASSWORD_LOCK_TIME 1
PASSWORD_GRACE_TIME 2;

--crear 3 usuarios--
CREATE USER PEPITO1 IDENTIFIED BY PEPITO1
DEFAULT TABLESPACE  COORDINADORA
PROFILE CLERK;

GRANT CREATE SESSION TO PEPITO1;

CREATE USER PEPITO2 IDENTIFIED BY PEPITO2
DEFAULT TABLESPACE  COORDINADORA
PROFILE DEVELOPMENT;

GRANT CREATE SESSION TO PEPITO2;

CREATE USER PEPITO3 IDENTIFIED BY PEPITO3
DEFAULT TABLESPACE  COORDINADORA
PROFILE OPERATIVE;

ALTER USER PEPITO3 ACCOUNT LOCK;

GRANT CREATE SESSION TO PEPITO3;
