
--------------------------------------------------------
-- Archivo creado  - viernes-abril-26-2019   
--------------------------------------------------------
DROP TABLE "AMARTINEZG"."CENTRO_CARGAS";
DROP TABLE "AMARTINEZG"."CIUDADES";
DROP TABLE "AMARTINEZG"."CLIENTES";
DROP TABLE "AMARTINEZG"."CODIGOS_POSTAL";
DROP TABLE "AMARTINEZG"."DEPARTAMENTOS";
DROP TABLE "AMARTINEZG"."DESPACHOS";
DROP TABLE "AMARTINEZG"."EMPLEADOS";
DROP TABLE "AMARTINEZG"."INVENTARIO_VEHICULOS";
DROP TABLE "AMARTINEZG"."MANTENIMIENTOS";
DROP TABLE "AMARTINEZG"."MANTENIMIENTOS_DETALLE";
DROP TABLE "AMARTINEZG"."SEGUIMIENTOS";
--------------------------------------------------------
--  DDL for Table CENTRO_CARGAS
--------------------------------------------------------

  CREATE TABLE "AMARTINEZG"."CENTRO_CARGAS" 
   (	"ID" NUMBER(*,0), 
	"DEPARTAMENTOS_ID" NUMBER(*,0), 
	"NOMBRES" VARCHAR2(50), 
	"DIRECCION" VARCHAR2(50), 
	"TELEFONO" VARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COORDINADORA" ;
--------------------------------------------------------
--  DDL for Table CIUDADES
--------------------------------------------------------

  CREATE TABLE "AMARTINEZG"."CIUDADES" 
   (	"ID" NUMBER(*,0), 
	"DEPARTAMENTOS_ID" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COORDINADORA" ;
--------------------------------------------------------
--  DDL for Table CLIENTES
--------------------------------------------------------

  CREATE TABLE "AMARTINEZG"."CLIENTES" 
   (	"ID" NUMBER(*,0), 
	"DEPARTAMENTOS_ID" NUMBER(*,0), 
	"TIPO_DOCUMENTO" VARCHAR2(50), 
	"IDENTIFICACION" VARCHAR2(20), 
	"NOMBRES" VARCHAR2(50), 
	"DIRECCION" VARCHAR2(50), 
	"DIRECCION_2" VARCHAR2(50), 
	"CELULAR" VARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COORDINADORA" ;
--------------------------------------------------------
--  DDL for Table CODIGOS_POSTAL
--------------------------------------------------------

  CREATE TABLE "AMARTINEZG"."CODIGOS_POSTAL" 
   (	"ID" NUMBER(*,0), 
	"CIUDADES_ID" NUMBER(*,0), 
	"CODIGO" VARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COORDINADORA" ;
--------------------------------------------------------
--  DDL for Table DEPARTAMENTOS
--------------------------------------------------------

  CREATE TABLE "AMARTINEZG"."DEPARTAMENTOS" 
   (	"ID" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COORDINADORA" ;
--------------------------------------------------------
--  DDL for Table DESPACHOS
--------------------------------------------------------

  CREATE TABLE "AMARTINEZG"."DESPACHOS" 
   (	"ID" NUMBER(*,0), 
	"CLIENTES_ID" NUMBER(*,0), 
	"ANCHO" NUMBER, 
	"LARGO" NUMBER, 
	"ALTO" NUMBER, 
	"PESO" NUMBER, 
	"PESO_VOLUMEN" NUMBER, 
	"TIPO_SERVICIO" VARCHAR2(50), 
	"DIRECCION_DESTINATARIO" VARCHAR2(50), 
	"FECHA_DESPACHO" DATE, 
	"HORA_DESPACHO" VARCHAR2(50), 
	"FECHA_ENTREGA" DATE, 
	"HORA_ENTREGA" VARCHAR2(50), 
	"OBSERVACION" VARCHAR2(250), 
	"UNIDADES" NUMBER, 
	"FLETE_FIJO" NUMBER, 
	"FLETE_VARIABLE" NUMBER, 
	"OTROS" VARCHAR2(250), 
	"VALOR_SERVICIO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COORDINADORA" ;
--------------------------------------------------------
--  DDL for Table EMPLEADOS
--------------------------------------------------------

  CREATE TABLE "AMARTINEZG"."EMPLEADOS" 
   (	"ID" NUMBER(*,0), 
	"DEPARTAMENTOS_ID" NUMBER(*,0), 
	"CENTRO_CARGAS_ID" NUMBER(*,0), 
	"TIPO_DOCUMENTO" VARCHAR2(50), 
	"IDENTIFICACION" VARCHAR2(20), 
	"NOMBRES" VARCHAR2(50), 
	"DIRECCION" VARCHAR2(50), 
	"CARGO" VARCHAR2(50), 
	"SALARIO" VARCHAR2(50), 
	"JEFE_DIRECTOR" VARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COORDINADORA" ;
--------------------------------------------------------
--  DDL for Table INVENTARIO_VEHICULOS
--------------------------------------------------------

  CREATE TABLE "AMARTINEZG"."INVENTARIO_VEHICULOS" 
   (	"ID" NUMBER(*,0), 
	"CENTRO_CARGAS_ID" NUMBER(*,0), 
	"MARCA" VARCHAR2(50), 
	"MODELO" VARCHAR2(50), 
	"LINEA" VARCHAR2(50), 
	"TIPO_COMBUSTIBLE" VARCHAR2(50), 
	"KILOMETRAJE" NUMBER, 
	"CAPACIDAD" VARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COORDINADORA" ;
--------------------------------------------------------
--  DDL for Table MANTENIMIENTOS
--------------------------------------------------------

  CREATE TABLE "AMARTINEZG"."MANTENIMIENTOS" 
   (	"ID" NUMBER(*,0), 
	"EMPLEADOS_ID" NUMBER(*,0), 
	"INVENTARIO_VEHICULOS_ID" NUMBER(*,0), 
	"KILOMETRAJE" NUMBER(*,0), 
	"FECHA" DATE, 
	"HORA_ENTRADA" VARCHAR2(50), 
	"HORA_SALIDA" VARCHAR2(50), 
	"TIPO_MANTENIMIENTO" VARCHAR2(50), 
	"ESTADO" VARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COORDINADORA" ;
--------------------------------------------------------
--  DDL for Table MANTENIMIENTOS_DETALLE
--------------------------------------------------------

  CREATE TABLE "AMARTINEZG"."MANTENIMIENTOS_DETALLE" 
   (	"ID" NUMBER(*,0), 
	"MANTENIMIENTOS_ID" NUMBER(*,0), 
	"REVISION" VARCHAR2(150), 
	"ESTADO" VARCHAR2(50), 
	"OBSERVACION" VARCHAR2(250)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COORDINADORA" ;
--------------------------------------------------------
--  DDL for Table SEGUIMIENTOS
--------------------------------------------------------

  CREATE TABLE "AMARTINEZG"."SEGUIMIENTOS" 
   (	"ID" NUMBER(*,0), 
	"DESPACHOS_ID" NUMBER(*,0), 
	"ESTADO" VARCHAR2(50), 
	"FECHA" DATE, 
	"HORA" VARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COORDINADORA" ;
REM INSERTING into AMARTINEZG.CENTRO_CARGAS
SET DEFINE OFF;
Insert into AMARTINEZG.CENTRO_CARGAS (ID,DEPARTAMENTOS_ID,NOMBRES,DIRECCION,TELEFONO) values ('1','5','TERMINAL DEL NORTE','CL 3 # 25 - 299 ','3007117457');
Insert into AMARTINEZG.CENTRO_CARGAS (ID,DEPARTAMENTOS_ID,NOMBRES,DIRECCION,TELEFONO) values ('2','8','TERMINAL DEL SUR','CL 105 A # 49 A - 29','3003070405');
Insert into AMARTINEZG.CENTRO_CARGAS (ID,DEPARTAMENTOS_ID,NOMBRES,DIRECCION,TELEFONO) values ('3','11','COORDINA A','CL 12 A # 38 - 81','3046684108');
Insert into AMARTINEZG.CENTRO_CARGAS (ID,DEPARTAMENTOS_ID,NOMBRES,DIRECCION,TELEFONO) values ('4','13','COORDINA B','CL 78 SUR # 40 - 135','3024104594');
Insert into AMARTINEZG.CENTRO_CARGAS (ID,DEPARTAMENTOS_ID,NOMBRES,DIRECCION,TELEFONO) values ('5','15','COORDINA C','CL 13 # 17 E - 19','3006791308');
Insert into AMARTINEZG.CENTRO_CARGAS (ID,DEPARTAMENTOS_ID,NOMBRES,DIRECCION,TELEFONO) values ('6','17','COORDINA C','KR 24 DD # 41 - 190 SUR','3002668146');
Insert into AMARTINEZG.CENTRO_CARGAS (ID,DEPARTAMENTOS_ID,NOMBRES,DIRECCION,TELEFONO) values ('7','18','COORDINA D','CL 10 B NORTE # 5 - 41','3008737162');
Insert into AMARTINEZG.CENTRO_CARGAS (ID,DEPARTAMENTOS_ID,NOMBRES,DIRECCION,TELEFONO) values ('8','19','COORDINA E','KR 46 # 86 - 72','3046401607');
Insert into AMARTINEZG.CENTRO_CARGAS (ID,DEPARTAMENTOS_ID,NOMBRES,DIRECCION,TELEFONO) values ('9','20','COORDINA F','CL 35 D # 89 - 33','3202355543');
Insert into AMARTINEZG.CENTRO_CARGAS (ID,DEPARTAMENTOS_ID,NOMBRES,DIRECCION,TELEFONO) values ('10','23','COORDINA G','KR 20 A # 10 B - 33','3023895628');
REM INSERTING into AMARTINEZG.CIUDADES
SET DEFINE OFF;
Insert into AMARTINEZG.CIUDADES (ID,DEPARTAMENTOS_ID,NOMBRE) values ('5674','5','SAN VICENTE');
Insert into AMARTINEZG.CIUDADES (ID,DEPARTAMENTOS_ID,NOMBRE) values ('5002','5','ABEJORRAL');
Insert into AMARTINEZG.CIUDADES (ID,DEPARTAMENTOS_ID,NOMBRE) values ('5360','5','ITAGÃƒÅ“I');
Insert into AMARTINEZG.CIUDADES (ID,DEPARTAMENTOS_ID,NOMBRE) values ('8421','8','LURUACO');
Insert into AMARTINEZG.CIUDADES (ID,DEPARTAMENTOS_ID,NOMBRE) values ('8758','8','SOLEDAD');
Insert into AMARTINEZG.CIUDADES (ID,DEPARTAMENTOS_ID,NOMBRE) values ('11001','11','LOCALIDAD ENGATIVA');
Insert into AMARTINEZG.CIUDADES (ID,DEPARTAMENTOS_ID,NOMBRE) values ('5321','5','GUATAPE');
Insert into AMARTINEZG.CIUDADES (ID,DEPARTAMENTOS_ID,NOMBRE) values ('5001','5','MEDELLIN');
Insert into AMARTINEZG.CIUDADES (ID,DEPARTAMENTOS_ID,NOMBRE) values ('5789','5','TAMESIS');
Insert into AMARTINEZG.CIUDADES (ID,DEPARTAMENTOS_ID,NOMBRE) values ('13620','13','SAN CRISTOBAL');
REM INSERTING into AMARTINEZG.CLIENTES
SET DEFINE OFF;
Insert into AMARTINEZG.CLIENTES (ID,DEPARTAMENTOS_ID,TIPO_DOCUMENTO,IDENTIFICACION,NOMBRES,DIRECCION,DIRECCION_2,CELULAR) values ('1','5','CEDULA DE CIUDADANIA','1128277','Katerine Deniseau','KR 22 A # 107 - 20 CS 1',null,'+62 (751) 313-0696');
Insert into AMARTINEZG.CLIENTES (ID,DEPARTAMENTOS_ID,TIPO_DOCUMENTO,IDENTIFICACION,NOMBRES,DIRECCION,DIRECCION_2,CELULAR) values ('2','8','CEDULA DE CIUDADANIA','394662','Russ Klamman','CL 103 # 23 A - 71 IN 202 ED SAN DIEGO','KR 21 B # 111 - 152','+7 (567) 509-0739');
Insert into AMARTINEZG.CLIENTES (ID,DEPARTAMENTOS_ID,TIPO_DOCUMENTO,IDENTIFICACION,NOMBRES,DIRECCION,DIRECCION_2,CELULAR) values ('3','11','CEDULA DE CIUDADANIA','8721128','Isadore Coxhead','KR 24 # 107 - 40','CL 115 # 22 A - 80 AP 201','+1 (427) 624-2218');
Insert into AMARTINEZG.CLIENTES (ID,DEPARTAMENTOS_ID,TIPO_DOCUMENTO,IDENTIFICACION,NOMBRES,DIRECCION,DIRECCION_2,CELULAR) values ('4','13','CEDULA DE CIUDADANIA','7188159475','Adriaens Giveen','CL 102 # 23 A - 55','CL 107 # 24 A - 08 IN 201 ED KARLA','+55 (410) 388-6425');
Insert into AMARTINEZG.CLIENTES (ID,DEPARTAMENTOS_ID,TIPO_DOCUMENTO,IDENTIFICACION,NOMBRES,DIRECCION,DIRECCION_2,CELULAR) values ('5','15','CEDULA DE CIUDADANIA','6475379611','Sophronia Jenny','CL 116 # 22 A - 53 AP 401','CL 101 # 22 A - 114 AP 3 1','+1 (139) 600-3305');
Insert into AMARTINEZG.CLIENTES (ID,DEPARTAMENTOS_ID,TIPO_DOCUMENTO,IDENTIFICACION,NOMBRES,DIRECCION,DIRECCION_2,CELULAR) values ('6','17','CEDULA DE CIUDADANIA','6026438858','Edi Kennady','CL 115 # 22 - 26 AP 101',null,'+63 (440) 627-1256');
Insert into AMARTINEZG.CLIENTES (ID,DEPARTAMENTOS_ID,TIPO_DOCUMENTO,IDENTIFICACION,NOMBRES,DIRECCION,DIRECCION_2,CELULAR) values ('7','18','CEDULA DE CIUDADANIA','5082008617','Winnie Milmoe','CL 106 # 24 - 115 TO DE AVIÃƒâ€˜ON AP 402','CL 114 # 22 - 74 AP 201','+86 (412) 435-6971');
Insert into AMARTINEZG.CLIENTES (ID,DEPARTAMENTOS_ID,TIPO_DOCUMENTO,IDENTIFICACION,NOMBRES,DIRECCION,DIRECCION_2,CELULAR) values ('8','19','CEDULA DE CIUDADANIA','4310843050','Tiler Ten Broek','CL 106 # 25 - 49 AP 501',null,'+86 (660) 325-9218');
Insert into AMARTINEZG.CLIENTES (ID,DEPARTAMENTOS_ID,TIPO_DOCUMENTO,IDENTIFICACION,NOMBRES,DIRECCION,DIRECCION_2,CELULAR) values ('9','20','CEDULA DE CIUDADANIA','4160809936','Raddy Daniell','CL 106 # 26 A - 05 TO 2 AP 204',null,'+53 (796) 808-8804');
Insert into AMARTINEZG.CLIENTES (ID,DEPARTAMENTOS_ID,TIPO_DOCUMENTO,IDENTIFICACION,NOMBRES,DIRECCION,DIRECCION_2,CELULAR) values ('10','23','CEDULA DE CIUDADANIA','5282616092','Lettie Carwardine','DG 20 # 101 - 27 AP 201',null,'+7 (771) 915-0834');
REM INSERTING into AMARTINEZG.CODIGOS_POSTAL
SET DEFINE OFF;
Insert into AMARTINEZG.CODIGOS_POSTAL (ID,CIUDADES_ID,CODIGO) values ('1','5674','54018');
Insert into AMARTINEZG.CODIGOS_POSTAL (ID,CIUDADES_ID,CODIGO) values ('2','5002','55030');
Insert into AMARTINEZG.CODIGOS_POSTAL (ID,CIUDADES_ID,CODIGO) values ('3','5360','55411');
Insert into AMARTINEZG.CODIGOS_POSTAL (ID,CIUDADES_ID,CODIGO) values ('4','5001','50032');
Insert into AMARTINEZG.CODIGOS_POSTAL (ID,CIUDADES_ID,CODIGO) values ('5','5360','55411');
REM INSERTING into AMARTINEZG.DEPARTAMENTOS
SET DEFINE OFF;
Insert into AMARTINEZG.DEPARTAMENTOS (ID,NOMBRE) values ('5','ANTIOQUIA');
Insert into AMARTINEZG.DEPARTAMENTOS (ID,NOMBRE) values ('8','ATLANTICO');
Insert into AMARTINEZG.DEPARTAMENTOS (ID,NOMBRE) values ('11','BOGOTA D.C.');
Insert into AMARTINEZG.DEPARTAMENTOS (ID,NOMBRE) values ('13','BOLIVAR');
Insert into AMARTINEZG.DEPARTAMENTOS (ID,NOMBRE) values ('15','BOYACA');
Insert into AMARTINEZG.DEPARTAMENTOS (ID,NOMBRE) values ('17','CALDAS');
Insert into AMARTINEZG.DEPARTAMENTOS (ID,NOMBRE) values ('18','CAQUETA');
Insert into AMARTINEZG.DEPARTAMENTOS (ID,NOMBRE) values ('19','CAUCA');
Insert into AMARTINEZG.DEPARTAMENTOS (ID,NOMBRE) values ('20','CESAR');
Insert into AMARTINEZG.DEPARTAMENTOS (ID,NOMBRE) values ('23','CORDOBA');
REM INSERTING into AMARTINEZG.DESPACHOS
SET DEFINE OFF;
Insert into AMARTINEZG.DESPACHOS (ID,CLIENTES_ID,ANCHO,LARGO,ALTO,PESO,PESO_VOLUMEN,TIPO_SERVICIO,DIRECCION_DESTINATARIO,FECHA_DESPACHO,HORA_DESPACHO,FECHA_ENTREGA,HORA_ENTREGA,OBSERVACION,UNIDADES,FLETE_FIJO,FLETE_VARIABLE,OTROS,VALOR_SERVICIO) values ('1','1','10','50','45','80','9000000','CARGA AEREA','KR 22 A # 107 - 20 CS 1',to_date('18/03/19','DD/MM/RR'),'02:35 p.m.',to_date('20/03/19','DD/MM/RR'),'11:20 a.m.','Sin Observaciones','23','10000','5000','0','12000');
Insert into AMARTINEZG.DESPACHOS (ID,CLIENTES_ID,ANCHO,LARGO,ALTO,PESO,PESO_VOLUMEN,TIPO_SERVICIO,DIRECCION_DESTINATARIO,FECHA_DESPACHO,HORA_DESPACHO,FECHA_ENTREGA,HORA_ENTREGA,OBSERVACION,UNIDADES,FLETE_FIJO,FLETE_VARIABLE,OTROS,VALOR_SERVICIO) values ('2','2','15','20','40','70','4800000','MERCANCIA','CL 103 # 23 A - 71 IN 202 ED SAN DIEGO',to_date('18/02/19','DD/MM/RR'),'11:35 a.m.',to_date('24/02/19','DD/MM/RR'),'11:35 a.m.','Sin Observaciones','65','10000','6000','0','12000');
Insert into AMARTINEZG.DESPACHOS (ID,CLIENTES_ID,ANCHO,LARGO,ALTO,PESO,PESO_VOLUMEN,TIPO_SERVICIO,DIRECCION_DESTINATARIO,FECHA_DESPACHO,HORA_DESPACHO,FECHA_ENTREGA,HORA_ENTREGA,OBSERVACION,UNIDADES,FLETE_FIJO,FLETE_VARIABLE,OTROS,VALOR_SERVICIO) values ('3','3','50','100','35','60','70000000','MENSAJERIA','KR 24 # 107 - 40',to_date('21/04/19','DD/MM/RR'),'12:40 p.m.',to_date('21/06/19','DD/MM/RR'),'12:35 p.m.','Sin Observaciones','78','10000','7000','0','12000');
Insert into AMARTINEZG.DESPACHOS (ID,CLIENTES_ID,ANCHO,LARGO,ALTO,PESO,PESO_VOLUMEN,TIPO_SERVICIO,DIRECCION_DESTINATARIO,FECHA_DESPACHO,HORA_DESPACHO,FECHA_ENTREGA,HORA_ENTREGA,OBSERVACION,UNIDADES,FLETE_FIJO,FLETE_VARIABLE,OTROS,VALOR_SERVICIO) values ('4','4','25','10','30','50','3000000','FIRMA DE DOCUMENTOS','CL 102 # 23 A - 55',to_date('27/01/19','DD/MM/RR'),'12:35 p.m.',to_date('14/08/19','DD/MM/RR'),'12:40 p.m.','Sin Observaciones','4','10000','8000','0','12000');
Insert into AMARTINEZG.DESPACHOS (ID,CLIENTES_ID,ANCHO,LARGO,ALTO,PESO,PESO_VOLUMEN,TIPO_SERVICIO,DIRECCION_DESTINATARIO,FECHA_DESPACHO,HORA_DESPACHO,FECHA_ENTREGA,HORA_ENTREGA,OBSERVACION,UNIDADES,FLETE_FIJO,FLETE_VARIABLE,OTROS,VALOR_SERVICIO) values ('5','5','23','5','25','120','1150000','RADICACION DE DOCUMENTOS','CL 116 # 22 A - 53 AP 401',to_date('25/01/19','DD/MM/RR'),'10:35 a.m.',to_date('21/03/19','DD/MM/RR'),'11:40 a.m.','Sin Observaciones','15','10000','9000','0','12000');
Insert into AMARTINEZG.DESPACHOS (ID,CLIENTES_ID,ANCHO,LARGO,ALTO,PESO,PESO_VOLUMEN,TIPO_SERVICIO,DIRECCION_DESTINATARIO,FECHA_DESPACHO,HORA_DESPACHO,FECHA_ENTREGA,HORA_ENTREGA,OBSERVACION,UNIDADES,FLETE_FIJO,FLETE_VARIABLE,OTROS,VALOR_SERVICIO) values ('6','6','30','10','20','150','2400000','CARGA AEREA','CL 8 C # 87 B - 40 CS 80 ET 1',to_date('15/02/19','DD/MM/RR'),'11:40 a.m.',to_date('19/02/19','DD/MM/RR'),'10:35 a.m.','Sin Observaciones','27','10000','20000','0','12000');
Insert into AMARTINEZG.DESPACHOS (ID,CLIENTES_ID,ANCHO,LARGO,ALTO,PESO,PESO_VOLUMEN,TIPO_SERVICIO,DIRECCION_DESTINATARIO,FECHA_DESPACHO,HORA_DESPACHO,FECHA_ENTREGA,HORA_ENTREGA,OBSERVACION,UNIDADES,FLETE_FIJO,FLETE_VARIABLE,OTROS,VALOR_SERVICIO) values ('7','7','45','15','15','130','4050000','MERCANCIA','KR 149 A # 139 - 28 PI 2',to_date('16/07/19','DD/MM/RR'),'03:35 p.m.',to_date('16/09/19','DD/MM/RR'),'11:20 a.m.','Sin Observaciones','75','10000','25000','0','12000');
Insert into AMARTINEZG.DESPACHOS (ID,CLIENTES_ID,ANCHO,LARGO,ALTO,PESO,PESO_VOLUMEN,TIPO_SERVICIO,DIRECCION_DESTINATARIO,FECHA_DESPACHO,HORA_DESPACHO,FECHA_ENTREGA,HORA_ENTREGA,OBSERVACION,UNIDADES,FLETE_FIJO,FLETE_VARIABLE,OTROS,VALOR_SERVICIO) values ('8','8','43','50','10','110','8600000','MENSAJERIA','KR 12 # 10 - 16',to_date('16/11/19','DD/MM/RR'),'11:20 a.m.',to_date('20/12/19','DD/MM/RR'),'03:35 p.m.','Sin Observaciones','94','10000','15000','0','12000');
Insert into AMARTINEZG.DESPACHOS (ID,CLIENTES_ID,ANCHO,LARGO,ALTO,PESO,PESO_VOLUMEN,TIPO_SERVICIO,DIRECCION_DESTINATARIO,FECHA_DESPACHO,HORA_DESPACHO,FECHA_ENTREGA,HORA_ENTREGA,OBSERVACION,UNIDADES,FLETE_FIJO,FLETE_VARIABLE,OTROS,VALOR_SERVICIO) values ('9','9','67','25','45','40','30150000','FIRMA DE DOCUMENTOS','TV 54 # 80 - 26 BL 1 AP 305',to_date('14/02/19','DD/MM/RR'),'12:25 p.m.',to_date('13/04/19','DD/MM/RR'),'12:15 p.m.','Sin Observaciones','11','10000','18000','0','12000');
Insert into AMARTINEZG.DESPACHOS (ID,CLIENTES_ID,ANCHO,LARGO,ALTO,PESO,PESO_VOLUMEN,TIPO_SERVICIO,DIRECCION_DESTINATARIO,FECHA_DESPACHO,HORA_DESPACHO,FECHA_ENTREGA,HORA_ENTREGA,OBSERVACION,UNIDADES,FLETE_FIJO,FLETE_VARIABLE,OTROS,VALOR_SERVICIO) values ('10','10','80','23','40','30','29440000','RADICACION DE DOCUMENTOS','CL 82 SUR # 58 - 34 IN 313',to_date('27/01/19','DD/MM/RR'),'12:15 p.m.',to_date('26/05/19','DD/MM/RR'),'12:25 p.m.','Sin Observaciones','8','10000','30000','0','12000');
REM INSERTING into AMARTINEZG.EMPLEADOS
SET DEFINE OFF;
Insert into AMARTINEZG.EMPLEADOS (ID,DEPARTAMENTOS_ID,CENTRO_CARGAS_ID,TIPO_DOCUMENTO,IDENTIFICACION,NOMBRES,DIRECCION,CARGO,SALARIO,JEFE_DIRECTOR) values ('1','5','1','CEDULA DE CIUDADANIA','72127112','ANIBAL MIGUEL ARTEAGA TORREGROSA','CL 8 C # 87 B - 40 CS 80 ET 1','ADMINISTRADOR','3000000','ANIBAL MIGUEL ARTEAGA TORREGROSA');
Insert into AMARTINEZG.EMPLEADOS (ID,DEPARTAMENTOS_ID,CENTRO_CARGAS_ID,TIPO_DOCUMENTO,IDENTIFICACION,NOMBRES,DIRECCION,CARGO,SALARIO,JEFE_DIRECTOR) values ('2','8','2','CEDULA DE CIUDADANIA','1019131366','SONIA ESTHER CORDOBA CHANTACA ','KR 149 A # 139 - 28 PI 2','OPERARIO','1500000','ANIBAL MIGUEL ARTEAGA TORREGROSA');
Insert into AMARTINEZG.EMPLEADOS (ID,DEPARTAMENTOS_ID,CENTRO_CARGAS_ID,TIPO_DOCUMENTO,IDENTIFICACION,NOMBRES,DIRECCION,CARGO,SALARIO,JEFE_DIRECTOR) values ('3','11','3','CEDULA DE CIUDADANIA','32803321','SUGEIDY MARIA OTERO DE LA CRUZ ','KR 12 # 10 - 16','CONDUCTOR','1000000','ANIBAL MIGUEL ARTEAGA TORREGROSA');
Insert into AMARTINEZG.EMPLEADOS (ID,DEPARTAMENTOS_ID,CENTRO_CARGAS_ID,TIPO_DOCUMENTO,IDENTIFICACION,NOMBRES,DIRECCION,CARGO,SALARIO,JEFE_DIRECTOR) values ('4','13','4','CEDULA DE CIUDADANIA','1143399861','LORENA MARCELA PEREZ CASA ','TV 54 # 80 - 26 BL 1 AP 305','OPERARIO','1300000','ANIBAL MIGUEL ARTEAGA TORREGROSA');
Insert into AMARTINEZG.EMPLEADOS (ID,DEPARTAMENTOS_ID,CENTRO_CARGAS_ID,TIPO_DOCUMENTO,IDENTIFICACION,NOMBRES,DIRECCION,CARGO,SALARIO,JEFE_DIRECTOR) values ('5','15','5','CEDULA DE CIUDADANIA','43747818','GLADYS RAQUEL ORTIZ ZULETA','CL 82 SUR # 58 - 34 IN 313','CONDUCTOR','1500000','ANIBAL MIGUEL ARTEAGA TORREGROSA');
Insert into AMARTINEZG.EMPLEADOS (ID,DEPARTAMENTOS_ID,CENTRO_CARGAS_ID,TIPO_DOCUMENTO,IDENTIFICACION,NOMBRES,DIRECCION,CARGO,SALARIO,JEFE_DIRECTOR) values ('6','17','1','CEDULA DE CIUDADANIA','1016100504','MARIA PAULA MENDEZ TIBAMOSO ','CL 17 F # 113 - 23 PI 3','CARTERA','200000','ANIBAL MIGUEL ARTEAGA TORREGROSA');
Insert into AMARTINEZG.EMPLEADOS (ID,DEPARTAMENTOS_ID,CENTRO_CARGAS_ID,TIPO_DOCUMENTO,IDENTIFICACION,NOMBRES,DIRECCION,CARGO,SALARIO,JEFE_DIRECTOR) values ('7','18','7','CEDULA DE CIUDADANIA','1019115453','JASBLEIDY YULIANA MULOZ CHAVES ','CL 151 B # 115 - 81 BL 79 AP 302','CONDUCTOR','1500000','ANIBAL MIGUEL ARTEAGA TORREGROSA');
Insert into AMARTINEZG.EMPLEADOS (ID,DEPARTAMENTOS_ID,CENTRO_CARGAS_ID,TIPO_DOCUMENTO,IDENTIFICACION,NOMBRES,DIRECCION,CARGO,SALARIO,JEFE_DIRECTOR) values ('8','19','8','CEDULA DE CIUDADANIA','1014243875','JORDAN DAVID CARDONA GRIJALBA ','CL 70 A # 110 - 75','MENSAJERO','1000000','ANIBAL MIGUEL ARTEAGA TORREGROSA');
Insert into AMARTINEZG.EMPLEADOS (ID,DEPARTAMENTOS_ID,CENTRO_CARGAS_ID,TIPO_DOCUMENTO,IDENTIFICACION,NOMBRES,DIRECCION,CARGO,SALARIO,JEFE_DIRECTOR) values ('9','20','1','CEDULA DE CIUDADANIA','52166307','SANDRA XIMENA DIAZ ROMERO','CL 18 SUR # 9 A - 24 PI 3','ASEO','900000','ANIBAL MIGUEL ARTEAGA TORREGROSA');
Insert into AMARTINEZG.EMPLEADOS (ID,DEPARTAMENTOS_ID,CENTRO_CARGAS_ID,TIPO_DOCUMENTO,IDENTIFICACION,NOMBRES,DIRECCION,CARGO,SALARIO,JEFE_DIRECTOR) values ('10','23','10','CEDULA DE CIUDADANIA','51973670','OLGA PATRICIA MARTINEZ BOBADILLA','CL 21 # 88 A - 79 CS 177','MENSAJERO','950000','ANIBAL MIGUEL ARTEAGA TORREGROSA');
REM INSERTING into AMARTINEZG.INVENTARIO_VEHICULOS
SET DEFINE OFF;
Insert into AMARTINEZG.INVENTARIO_VEHICULOS (ID,CENTRO_CARGAS_ID,MARCA,MODELO,LINEA,TIPO_COMBUSTIBLE,KILOMETRAJE,CAPACIDAD) values ('1','1','Chevrolet','2009','NPR','GASOLINA','246900','700 KG');
Insert into AMARTINEZG.INVENTARIO_VEHICULOS (ID,CENTRO_CARGAS_ID,MARCA,MODELO,LINEA,TIPO_COMBUSTIBLE,KILOMETRAJE,CAPACIDAD) values ('2','2','Kia','2014','HINNO','DIESEL','133769','3,3 TON');
Insert into AMARTINEZG.INVENTARIO_VEHICULOS (ID,CENTRO_CARGAS_ID,MARCA,MODELO,LINEA,TIPO_COMBUSTIBLE,KILOMETRAJE,CAPACIDAD) values ('3','1','Chevrolet','2019','NPR','GASOLINA','20783','2,5 TON');
Insert into AMARTINEZG.INVENTARIO_VEHICULOS (ID,CENTRO_CARGAS_ID,MARCA,MODELO,LINEA,TIPO_COMBUSTIBLE,KILOMETRAJE,CAPACIDAD) values ('4','2','Kia','2015','HINNO','DIESEL','123977','3,5 TON');
Insert into AMARTINEZG.INVENTARIO_VEHICULOS (ID,CENTRO_CARGAS_ID,MARCA,MODELO,LINEA,TIPO_COMBUSTIBLE,KILOMETRAJE,CAPACIDAD) values ('5','1','Chevrolet','2011','NPR','GASOLINA','198654','700 KG');
Insert into AMARTINEZG.INVENTARIO_VEHICULOS (ID,CENTRO_CARGAS_ID,MARCA,MODELO,LINEA,TIPO_COMBUSTIBLE,KILOMETRAJE,CAPACIDAD) values ('6','2','Kia','2016','HINNO','DIESEL','127894','5 TON');
Insert into AMARTINEZG.INVENTARIO_VEHICULOS (ID,CENTRO_CARGAS_ID,MARCA,MODELO,LINEA,TIPO_COMBUSTIBLE,KILOMETRAJE,CAPACIDAD) values ('7','1','Chevrolet','2012','NPR','GASOLINA','112489','700 KG');
Insert into AMARTINEZG.INVENTARIO_VEHICULOS (ID,CENTRO_CARGAS_ID,MARCA,MODELO,LINEA,TIPO_COMBUSTIBLE,KILOMETRAJE,CAPACIDAD) values ('8','2','Kia','2017','HINNO','DIESEL','78934','6 TON');
Insert into AMARTINEZG.INVENTARIO_VEHICULOS (ID,CENTRO_CARGAS_ID,MARCA,MODELO,LINEA,TIPO_COMBUSTIBLE,KILOMETRAJE,CAPACIDAD) values ('9','1','Chevrolet','2013','NPR','GASOLINA','289357','2,8 TON');
Insert into AMARTINEZG.INVENTARIO_VEHICULOS (ID,CENTRO_CARGAS_ID,MARCA,MODELO,LINEA,TIPO_COMBUSTIBLE,KILOMETRAJE,CAPACIDAD) values ('10','2','Kia','2018','HINNO','DIESEL','50589','11 TON');
REM INSERTING into AMARTINEZG.MANTENIMIENTOS
SET DEFINE OFF;
Insert into AMARTINEZG.MANTENIMIENTOS (ID,EMPLEADOS_ID,INVENTARIO_VEHICULOS_ID,KILOMETRAJE,FECHA,HORA_ENTRADA,HORA_SALIDA,TIPO_MANTENIMIENTO,ESTADO) values ('1','10','10','50589',to_date('18/03/19','DD/MM/RR'),'07:35 a.m.','02:35 p.m.','5000 KILOMETROS','REALIZADO');
Insert into AMARTINEZG.MANTENIMIENTOS (ID,EMPLEADOS_ID,INVENTARIO_VEHICULOS_ID,KILOMETRAJE,FECHA,HORA_ENTRADA,HORA_SALIDA,TIPO_MANTENIMIENTO,ESTADO) values ('2','5','9','198654',to_date('24/02/19','DD/MM/RR'),'09:35 a.m.','11:35 a.m.','5000 KILOMETROS','REALIZADO');
Insert into AMARTINEZG.MANTENIMIENTOS (ID,EMPLEADOS_ID,INVENTARIO_VEHICULOS_ID,KILOMETRAJE,FECHA,HORA_ENTRADA,HORA_SALIDA,TIPO_MANTENIMIENTO,ESTADO) values ('3','9','8','289357',to_date('21/01/19','DD/MM/RR'),'10:40 a.m.','12:40 p.m.','10,000 KILOMETROS','REALIZADO');
Insert into AMARTINEZG.MANTENIMIENTOS (ID,EMPLEADOS_ID,INVENTARIO_VEHICULOS_ID,KILOMETRAJE,FECHA,HORA_ENTRADA,HORA_SALIDA,TIPO_MANTENIMIENTO,ESTADO) values ('4','3','7','20783',to_date('30/01/19','DD/MM/RR'),'07:10 a.m.','-','20,000 KILOMETROS','PENDIENTE');
Insert into AMARTINEZG.MANTENIMIENTOS (ID,EMPLEADOS_ID,INVENTARIO_VEHICULOS_ID,KILOMETRAJE,FECHA,HORA_ENTRADA,HORA_SALIDA,TIPO_MANTENIMIENTO,ESTADO) values ('5','2','6','133769',to_date('19/01/19','DD/MM/RR'),'10:10 a.m.','-','20,000 KILOMETROS','PENDIENTE');
Insert into AMARTINEZG.MANTENIMIENTOS (ID,EMPLEADOS_ID,INVENTARIO_VEHICULOS_ID,KILOMETRAJE,FECHA,HORA_ENTRADA,HORA_SALIDA,TIPO_MANTENIMIENTO,ESTADO) values ('6','6','5','127894',to_date('28/03/19','DD/MM/RR'),'01:28 p.m.','03:28 p.m.','5000 KILOMETROS','NO REALIZADO');
Insert into AMARTINEZG.MANTENIMIENTOS (ID,EMPLEADOS_ID,INVENTARIO_VEHICULOS_ID,KILOMETRAJE,FECHA,HORA_ENTRADA,HORA_SALIDA,TIPO_MANTENIMIENTO,ESTADO) values ('7','8','4','78934',to_date('27/02/19','DD/MM/RR'),'03:30 p.m.','05:30 p.m.','40,000 KILOMETROS','REALIZADO');
Insert into AMARTINEZG.MANTENIMIENTOS (ID,EMPLEADOS_ID,INVENTARIO_VEHICULOS_ID,KILOMETRAJE,FECHA,HORA_ENTRADA,HORA_SALIDA,TIPO_MANTENIMIENTO,ESTADO) values ('8','6','3','127894',to_date('18/03/19','DD/MM/RR'),'07:35 a.m.','12:35 p.m.','40,000 KILOMETROS','REALIZADO');
Insert into AMARTINEZG.MANTENIMIENTOS (ID,EMPLEADOS_ID,INVENTARIO_VEHICULOS_ID,KILOMETRAJE,FECHA,HORA_ENTRADA,HORA_SALIDA,TIPO_MANTENIMIENTO,ESTADO) values ('9','6','2','127894',to_date('18/02/19','DD/MM/RR'),'03:29 p.m.','-','100,000 KILOMETROS','PENDIENTE');
Insert into AMARTINEZG.MANTENIMIENTOS (ID,EMPLEADOS_ID,INVENTARIO_VEHICULOS_ID,KILOMETRAJE,FECHA,HORA_ENTRADA,HORA_SALIDA,TIPO_MANTENIMIENTO,ESTADO) values ('10','5','1','198654',to_date('18/01/19','DD/MM/RR'),'04:35 p.m.','-','50,000 KILOMETROS','PENDIENTE');
REM INSERTING into AMARTINEZG.MANTENIMIENTOS_DETALLE
SET DEFINE OFF;
Insert into AMARTINEZG.MANTENIMIENTOS_DETALLE (ID,MANTENIMIENTOS_ID,REVISION,ESTADO,OBSERVACION) values ('1','10','Cambiar el aceite y el filtro del mismo y el del aire','NO REALIZADO','sin Observaciones');
Insert into AMARTINEZG.MANTENIMIENTOS_DETALLE (ID,MANTENIMIENTOS_ID,REVISION,ESTADO,OBSERVACION) values ('2','9','Funcionamiento de las luces y del tablero de mando','NO REALIZADO','sin Observaciones');
Insert into AMARTINEZG.MANTENIMIENTOS_DETALLE (ID,MANTENIMIENTOS_ID,REVISION,ESTADO,OBSERVACION) values ('3','8','AlineaciÃ³n, balanceo y rotaciÃ³n de las llantas para garantizar un desgaste parejo','NO REALIZADO','sin Observaciones');
Insert into AMARTINEZG.MANTENIMIENTOS_DETALLE (ID,MANTENIMIENTOS_ID,REVISION,ESTADO,OBSERVACION) values ('4','7','ReposiciÃ³n del Filtro de aire y de combustible','NO REALIZADO','sin Observaciones');
Insert into AMARTINEZG.MANTENIMIENTOS_DETALLE (ID,MANTENIMIENTOS_ID,REVISION,ESTADO,OBSERVACION) values ('5','6','Debes repetir el mantenimiento de los 30.000 kilÃ³metros y adicionalmente hacer el mantenimiento y sondeo del radiador','NO REALIZADO','sin Observaciones');
Insert into AMARTINEZG.MANTENIMIENTOS_DETALLE (ID,MANTENIMIENTOS_ID,REVISION,ESTADO,OBSERVACION) values ('6','5','Repetir el mantenimiento de los 30.000 kilÃ³metros y adicionalmente sincronizar el motor de inyecciÃ³n o de carburador y ajustar la suspensiÃ³n','NO REALIZADO','sin Observaciones');
Insert into AMARTINEZG.MANTENIMIENTOS_DETALLE (ID,MANTENIMIENTOS_ID,REVISION,ESTADO,OBSERVACION) values ('7','4','Alinear el vehÃ­culo','NO REALIZADO','sin Observaciones');
Insert into AMARTINEZG.MANTENIMIENTOS_DETALLE (ID,MANTENIMIENTOS_ID,REVISION,ESTADO,OBSERVACION) values ('8','3','Sincronizar el motor','NO REALIZADO','sin Observaciones');
Insert into AMARTINEZG.MANTENIMIENTOS_DETALLE (ID,MANTENIMIENTOS_ID,REVISION,ESTADO,OBSERVACION) values ('9','2','Cambiar las pastillas y el lÃ­quido de frenos, bujÃ­as de encendido, cables de alta y correas','NO REALIZADO','sin Observaciones');
Insert into AMARTINEZG.MANTENIMIENTOS_DETALLE (ID,MANTENIMIENTOS_ID,REVISION,ESTADO,OBSERVACION) values ('10','1','Realizar peritaje especializado para prevenciÃ³n de fallas','NO REALIZADO','sin Observaciones');
REM INSERTING into AMARTINEZG.SEGUIMIENTOS
SET DEFINE OFF;
Insert into AMARTINEZG.SEGUIMIENTOS (ID,DESPACHOS_ID,ESTADO,FECHA,HORA) values ('1','9','A RECIBIR',to_date('18/01/19','DD/MM/RR'),'02:35 p.m.');
Insert into AMARTINEZG.SEGUIMIENTOS (ID,DESPACHOS_ID,ESTADO,FECHA,HORA) values ('2','8','EN TERMINAL ORIGEN',to_date('14/02/19','DD/MM/RR'),'11:35 a.m.');
Insert into AMARTINEZG.SEGUIMIENTOS (ID,DESPACHOS_ID,ESTADO,FECHA,HORA) values ('3','7','EN TRANSPORTE',to_date('21/03/19','DD/MM/RR'),'12:40 p.m.');
Insert into AMARTINEZG.SEGUIMIENTOS (ID,DESPACHOS_ID,ESTADO,FECHA,HORA) values ('4','6','EN TERMINAL DESTINO',to_date('27/04/19','DD/MM/RR'),'12:35 p.m.');
Insert into AMARTINEZG.SEGUIMIENTOS (ID,DESPACHOS_ID,ESTADO,FECHA,HORA) values ('5','5','EN REPARTO',to_date('25/05/19','DD/MM/RR'),'10:35 a.m.');
Insert into AMARTINEZG.SEGUIMIENTOS (ID,DESPACHOS_ID,ESTADO,FECHA,HORA) values ('6','4','ENTREGADA',to_date('15/07/19','DD/MM/RR'),'11:40 a.m.');
Insert into AMARTINEZG.SEGUIMIENTOS (ID,DESPACHOS_ID,ESTADO,FECHA,HORA) values ('7','3','A RECIBIR',to_date('16/08/19','DD/MM/RR'),'03:35 p.m.');
Insert into AMARTINEZG.SEGUIMIENTOS (ID,DESPACHOS_ID,ESTADO,FECHA,HORA) values ('8','2','EN TERMINAL ORIGEN',to_date('16/09/19','DD/MM/RR'),'11:20 a.m.');
Insert into AMARTINEZG.SEGUIMIENTOS (ID,DESPACHOS_ID,ESTADO,FECHA,HORA) values ('9','10','EN TRANSPORTE',to_date('14/10/19','DD/MM/RR'),'12:25 p.m.');
Insert into AMARTINEZG.SEGUIMIENTOS (ID,DESPACHOS_ID,ESTADO,FECHA,HORA) values ('10','1','EN TERMINAL DESTINO',to_date('27/11/19','DD/MM/RR'),'12:15 p.m.');
--------------------------------------------------------
--  DDL for Index CENTRO_CARGAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AMARTINEZG"."CENTRO_CARGAS_PK" ON "AMARTINEZG"."CENTRO_CARGAS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COORDINADORA" ;
--------------------------------------------------------
--  DDL for Index CIUDADES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AMARTINEZG"."CIUDADES_PK" ON "AMARTINEZG"."CIUDADES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COORDINADORA" ;
--------------------------------------------------------
--  DDL for Index CLIENTES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AMARTINEZG"."CLIENTES_PK" ON "AMARTINEZG"."CLIENTES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COORDINADORA" ;
--------------------------------------------------------
--  DDL for Index CODIGOS_POSTAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AMARTINEZG"."CODIGOS_POSTAL_PK" ON "AMARTINEZG"."CODIGOS_POSTAL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COORDINADORA" ;
--------------------------------------------------------
--  DDL for Index DEPARTAMENTOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AMARTINEZG"."DEPARTAMENTOS_PK" ON "AMARTINEZG"."DEPARTAMENTOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COORDINADORA" ;
--------------------------------------------------------
--  DDL for Index DESPACHOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AMARTINEZG"."DESPACHOS_PK" ON "AMARTINEZG"."DESPACHOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COORDINADORA" ;
--------------------------------------------------------
--  DDL for Index EMPLEADOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AMARTINEZG"."EMPLEADOS_PK" ON "AMARTINEZG"."EMPLEADOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COORDINADORA" ;
--------------------------------------------------------
--  DDL for Index INVENTARIO_VEHICULOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AMARTINEZG"."INVENTARIO_VEHICULOS_PK" ON "AMARTINEZG"."INVENTARIO_VEHICULOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COORDINADORA" ;
--------------------------------------------------------
--  DDL for Index MANTENIMIENTOS_DETALLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AMARTINEZG"."MANTENIMIENTOS_DETALLE_PK" ON "AMARTINEZG"."MANTENIMIENTOS_DETALLE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COORDINADORA" ;
--------------------------------------------------------
--  DDL for Index MANTENIMIENTOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AMARTINEZG"."MANTENIMIENTOS_PK" ON "AMARTINEZG"."MANTENIMIENTOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COORDINADORA" ;
--------------------------------------------------------
--  DDL for Index SEGUIMIENTOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AMARTINEZG"."SEGUIMIENTOS_PK" ON "AMARTINEZG"."SEGUIMIENTOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COORDINADORA" ;
--------------------------------------------------------
--  Constraints for Table CENTRO_CARGAS
--------------------------------------------------------

  ALTER TABLE "AMARTINEZG"."CENTRO_CARGAS" ADD CONSTRAINT "CENTRO_CARGAS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COORDINADORA"  ENABLE;
  ALTER TABLE "AMARTINEZG"."CENTRO_CARGAS" MODIFY ("TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."CENTRO_CARGAS" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."CENTRO_CARGAS" MODIFY ("NOMBRES" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."CENTRO_CARGAS" MODIFY ("DEPARTAMENTOS_ID" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."CENTRO_CARGAS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CIUDADES
--------------------------------------------------------

  ALTER TABLE "AMARTINEZG"."CIUDADES" ADD CONSTRAINT "CIUDADES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COORDINADORA"  ENABLE;
  ALTER TABLE "AMARTINEZG"."CIUDADES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."CIUDADES" MODIFY ("DEPARTAMENTOS_ID" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."CIUDADES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENTES
--------------------------------------------------------

  ALTER TABLE "AMARTINEZG"."CLIENTES" ADD CONSTRAINT "CLIENTES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COORDINADORA"  ENABLE;
  ALTER TABLE "AMARTINEZG"."CLIENTES" ADD CONSTRAINT "CHK_TIPO_DOCUMENTO" CHECK (TIPO_DOCUMENTO IN ('CEDULA DE CIUDADANIA','PASAPORTE','CEDULA DE EXTRANJERIA','NIT')) ENABLE;
  ALTER TABLE "AMARTINEZG"."CLIENTES" MODIFY ("CELULAR" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."CLIENTES" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."CLIENTES" MODIFY ("NOMBRES" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."CLIENTES" MODIFY ("IDENTIFICACION" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."CLIENTES" MODIFY ("TIPO_DOCUMENTO" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."CLIENTES" MODIFY ("DEPARTAMENTOS_ID" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."CLIENTES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CODIGOS_POSTAL
--------------------------------------------------------

  ALTER TABLE "AMARTINEZG"."CODIGOS_POSTAL" ADD CONSTRAINT "CODIGOS_POSTAL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COORDINADORA"  ENABLE;
  ALTER TABLE "AMARTINEZG"."CODIGOS_POSTAL" MODIFY ("CODIGO" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."CODIGOS_POSTAL" MODIFY ("CIUDADES_ID" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."CODIGOS_POSTAL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEPARTAMENTOS
--------------------------------------------------------

  ALTER TABLE "AMARTINEZG"."DEPARTAMENTOS" ADD CONSTRAINT "DEPARTAMENTOS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COORDINADORA"  ENABLE;
  ALTER TABLE "AMARTINEZG"."DEPARTAMENTOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."DEPARTAMENTOS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DESPACHOS
--------------------------------------------------------

  ALTER TABLE "AMARTINEZG"."DESPACHOS" ADD CONSTRAINT "DESPACHOS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COORDINADORA"  ENABLE;
  ALTER TABLE "AMARTINEZG"."DESPACHOS" ADD CONSTRAINT "CHK_TIPO_SERVICIO" CHECK (TIPO_SERVICIO IN ('CARGA AEREA','MERCANCIA','MENSAJERIA','FIRMA DE DOCUMENTOS','RADICACION DE DOCUMENTOS')) ENABLE;
  ALTER TABLE "AMARTINEZG"."DESPACHOS" MODIFY ("VALOR_SERVICIO" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."DESPACHOS" MODIFY ("OTROS" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."DESPACHOS" MODIFY ("FLETE_VARIABLE" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."DESPACHOS" MODIFY ("FLETE_FIJO" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."DESPACHOS" MODIFY ("UNIDADES" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."DESPACHOS" MODIFY ("HORA_DESPACHO" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."DESPACHOS" MODIFY ("FECHA_DESPACHO" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."DESPACHOS" MODIFY ("DIRECCION_DESTINATARIO" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."DESPACHOS" MODIFY ("TIPO_SERVICIO" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."DESPACHOS" MODIFY ("PESO_VOLUMEN" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."DESPACHOS" MODIFY ("PESO" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."DESPACHOS" MODIFY ("ALTO" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."DESPACHOS" MODIFY ("LARGO" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."DESPACHOS" MODIFY ("ANCHO" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."DESPACHOS" MODIFY ("CLIENTES_ID" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."DESPACHOS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLEADOS
--------------------------------------------------------

  ALTER TABLE "AMARTINEZG"."EMPLEADOS" ADD CONSTRAINT "EMPLEADOS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COORDINADORA"  ENABLE;
  ALTER TABLE "AMARTINEZG"."EMPLEADOS" ADD CONSTRAINT "CHK_TIPO_DOCUMENTO_EMPLEADOS" CHECK (TIPO_DOCUMENTO IN ('CEDULA DE CIUDADANIA','PASAPORTE','CEDULA DE EXTRANJERIA')) ENABLE;
  ALTER TABLE "AMARTINEZG"."EMPLEADOS" MODIFY ("JEFE_DIRECTOR" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."EMPLEADOS" MODIFY ("SALARIO" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."EMPLEADOS" MODIFY ("CARGO" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."EMPLEADOS" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."EMPLEADOS" MODIFY ("NOMBRES" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."EMPLEADOS" MODIFY ("IDENTIFICACION" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."EMPLEADOS" MODIFY ("TIPO_DOCUMENTO" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."EMPLEADOS" MODIFY ("CENTRO_CARGAS_ID" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."EMPLEADOS" MODIFY ("DEPARTAMENTOS_ID" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."EMPLEADOS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table INVENTARIO_VEHICULOS
--------------------------------------------------------

  ALTER TABLE "AMARTINEZG"."INVENTARIO_VEHICULOS" ADD CONSTRAINT "INVENTARIO_VEHICULOS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COORDINADORA"  ENABLE;
  ALTER TABLE "AMARTINEZG"."INVENTARIO_VEHICULOS" ADD CONSTRAINT "CHK_CAPACIDAD" CHECK (CAPACIDAD IN ('2,5 TON','2,8 TON','3,3 TON','3,5 TON','5 TON','6 TON','11 TON','700 KG')) ENABLE;
  ALTER TABLE "AMARTINEZG"."INVENTARIO_VEHICULOS" ADD CONSTRAINT "CHK_TIPO_COMBUSTIBLE" CHECK (TIPO_COMBUSTIBLE IN ('DIESEL','GASOLINA')) ENABLE;
  ALTER TABLE "AMARTINEZG"."INVENTARIO_VEHICULOS" MODIFY ("CAPACIDAD" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."INVENTARIO_VEHICULOS" MODIFY ("KILOMETRAJE" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."INVENTARIO_VEHICULOS" MODIFY ("TIPO_COMBUSTIBLE" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."INVENTARIO_VEHICULOS" MODIFY ("LINEA" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."INVENTARIO_VEHICULOS" MODIFY ("MODELO" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."INVENTARIO_VEHICULOS" MODIFY ("MARCA" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."INVENTARIO_VEHICULOS" MODIFY ("CENTRO_CARGAS_ID" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."INVENTARIO_VEHICULOS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MANTENIMIENTOS
--------------------------------------------------------

  ALTER TABLE "AMARTINEZG"."MANTENIMIENTOS" ADD CONSTRAINT "MANTENIMIENTOS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COORDINADORA"  ENABLE;
  ALTER TABLE "AMARTINEZG"."MANTENIMIENTOS" ADD CONSTRAINT "CHK_ESTADO" CHECK (ESTADO IN ('REALIZADO','PENDIENTE','NO REALIZADO')) ENABLE;
  ALTER TABLE "AMARTINEZG"."MANTENIMIENTOS" ADD CONSTRAINT "CHK_TIPO_MANTENIMIENTO" CHECK (TIPO_MANTENIMIENTO IN ('5000 KILOMETROS','10,000 KILOMETROS','20,000 KILOMETROS','40,000 KILOMETROS','50,000 KILOMETROS','100,000 KILOMETROS')) ENABLE;
  ALTER TABLE "AMARTINEZG"."MANTENIMIENTOS" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."MANTENIMIENTOS" MODIFY ("TIPO_MANTENIMIENTO" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."MANTENIMIENTOS" MODIFY ("HORA_SALIDA" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."MANTENIMIENTOS" MODIFY ("HORA_ENTRADA" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."MANTENIMIENTOS" MODIFY ("FECHA" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."MANTENIMIENTOS" MODIFY ("KILOMETRAJE" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."MANTENIMIENTOS" MODIFY ("INVENTARIO_VEHICULOS_ID" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."MANTENIMIENTOS" MODIFY ("EMPLEADOS_ID" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."MANTENIMIENTOS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MANTENIMIENTOS_DETALLE
--------------------------------------------------------

  ALTER TABLE "AMARTINEZG"."MANTENIMIENTOS_DETALLE" ADD CONSTRAINT "MANTENIMIENTOS_DETALLE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COORDINADORA"  ENABLE;
  ALTER TABLE "AMARTINEZG"."MANTENIMIENTOS_DETALLE" ADD CONSTRAINT "CHK_ESTADO_DETALLE" CHECK (ESTADO IN ('REALIZADO','PENDIENTE','NO REALIZADO')) ENABLE;
  ALTER TABLE "AMARTINEZG"."MANTENIMIENTOS_DETALLE" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."MANTENIMIENTOS_DETALLE" MODIFY ("REVISION" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."MANTENIMIENTOS_DETALLE" MODIFY ("MANTENIMIENTOS_ID" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."MANTENIMIENTOS_DETALLE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SEGUIMIENTOS
--------------------------------------------------------

  ALTER TABLE "AMARTINEZG"."SEGUIMIENTOS" ADD CONSTRAINT "SEGUIMIENTOS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COORDINADORA"  ENABLE;
  ALTER TABLE "AMARTINEZG"."SEGUIMIENTOS" ADD CONSTRAINT "CHK_ESTADO_SEGUIMIENTOS" CHECK (ESTADO IN ('A RECIBIR','EN TERMINAL ORIGEN','EN TRANSPORTE','EN TERMINAL DESTINO','EN REPARTO','ENTREGADA')) ENABLE;
  ALTER TABLE "AMARTINEZG"."SEGUIMIENTOS" MODIFY ("HORA" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."SEGUIMIENTOS" MODIFY ("FECHA" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."SEGUIMIENTOS" MODIFY ("ESTADO" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."SEGUIMIENTOS" MODIFY ("DESPACHOS_ID" NOT NULL ENABLE);
  ALTER TABLE "AMARTINEZG"."SEGUIMIENTOS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CENTRO_CARGAS
--------------------------------------------------------

  ALTER TABLE "AMARTINEZG"."CENTRO_CARGAS" ADD CONSTRAINT "FK_CENTRO_CARGAS_DEPARTAMENTOS" FOREIGN KEY ("DEPARTAMENTOS_ID")
	  REFERENCES "AMARTINEZG"."DEPARTAMENTOS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CIUDADES
--------------------------------------------------------

  ALTER TABLE "AMARTINEZG"."CIUDADES" ADD CONSTRAINT "FK_CIUDADES_DEPARTAMENTOS" FOREIGN KEY ("DEPARTAMENTOS_ID")
	  REFERENCES "AMARTINEZG"."DEPARTAMENTOS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CLIENTES
--------------------------------------------------------

  ALTER TABLE "AMARTINEZG"."CLIENTES" ADD CONSTRAINT "FK_CLIENTES_DEPARTAMENTOS" FOREIGN KEY ("DEPARTAMENTOS_ID")
	  REFERENCES "AMARTINEZG"."DEPARTAMENTOS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CODIGOS_POSTAL
--------------------------------------------------------

  ALTER TABLE "AMARTINEZG"."CODIGOS_POSTAL" ADD CONSTRAINT "FK_CODIGOS_POSTAL_CIUDADES" FOREIGN KEY ("CIUDADES_ID")
	  REFERENCES "AMARTINEZG"."CIUDADES" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DESPACHOS
--------------------------------------------------------

  ALTER TABLE "AMARTINEZG"."DESPACHOS" ADD CONSTRAINT "FK_DESPACHO_CLIENTES" FOREIGN KEY ("CLIENTES_ID")
	  REFERENCES "AMARTINEZG"."CLIENTES" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLEADOS
--------------------------------------------------------

  ALTER TABLE "AMARTINEZG"."EMPLEADOS" ADD CONSTRAINT "FK_EMPLEADOS_CENTRO_CARGAS" FOREIGN KEY ("CENTRO_CARGAS_ID")
	  REFERENCES "AMARTINEZG"."CENTRO_CARGAS" ("ID") ENABLE;
  ALTER TABLE "AMARTINEZG"."EMPLEADOS" ADD CONSTRAINT "FK_EMPLEADOS_DEPARTAMENTOS" FOREIGN KEY ("DEPARTAMENTOS_ID")
	  REFERENCES "AMARTINEZG"."DEPARTAMENTOS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INVENTARIO_VEHICULOS
--------------------------------------------------------

  ALTER TABLE "AMARTINEZG"."INVENTARIO_VEHICULOS" ADD CONSTRAINT "FK_INVENT_VEHI_CENTRO_CARGAS" FOREIGN KEY ("CENTRO_CARGAS_ID")
	  REFERENCES "AMARTINEZG"."CENTRO_CARGAS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MANTENIMIENTOS
--------------------------------------------------------

  ALTER TABLE "AMARTINEZG"."MANTENIMIENTOS" ADD CONSTRAINT "FK_MANTENIMIENTOS_EMPLEADOS" FOREIGN KEY ("EMPLEADOS_ID")
	  REFERENCES "AMARTINEZG"."EMPLEADOS" ("ID") ENABLE;
  ALTER TABLE "AMARTINEZG"."MANTENIMIENTOS" ADD CONSTRAINT "FK_MANTENIMIENTOS_INVENT_VEHI" FOREIGN KEY ("INVENTARIO_VEHICULOS_ID")
	  REFERENCES "AMARTINEZG"."INVENTARIO_VEHICULOS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MANTENIMIENTOS_DETALLE
--------------------------------------------------------

  ALTER TABLE "AMARTINEZG"."MANTENIMIENTOS_DETALLE" ADD CONSTRAINT "FK_MANTENIMI_DETALLE_MANTENIMI" FOREIGN KEY ("MANTENIMIENTOS_ID")
	  REFERENCES "AMARTINEZG"."MANTENIMIENTOS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SEGUIMIENTOS
--------------------------------------------------------

  ALTER TABLE "AMARTINEZG"."SEGUIMIENTOS" ADD CONSTRAINT "FK_SEGUIMIENTOS_DESPACHOS" FOREIGN KEY ("DESPACHOS_ID")
	  REFERENCES "AMARTINEZG"."DESPACHOS" ("ID") ENABLE;
